### ISSUE TITLE
Could not find the required DatasetRecord in the Catalog

### ISSUE THREAD

**Issue by JianChen123** [inovexcorp/mobi#3]
I got this error when I ran following command. I've double checked that the Dataset IRI is correct (I copied Dataset IRI on dataset edit popup.) What could be the problem?

mobi:import -d http://mobi.com/dataset/96a5eec5-c9d2-4d0a-89d0-953e8c2de418 <path to my nt file>

**Comment by mnmercer** [comment]
There is a difference between the "dataset IRI" and the "dataset record IRI". Each dataset in the application are cataloged with a `DatasetRecord` which is how they are identified since it includes some other information such as which repository the dataset is within and attached ontologies. The `mobi:import` command uses the dataset record IRI to identify which dataset to import data into.

If you are using version 1.11 of the application, you can actually import data into a dataset within the UI by going to the Datasets module in the application, clicking on the three dots button of the dataset in question, then clicking on "Upload Data". We are working on more intuitive ways to retrieve the IRI of the record itself, but if you do find you need a record IRI, you can run the following SPARQL query in the Query engine under the Discover module. Look in the results for a `recordIRI` with the `title` of the record you are trying to find and that includes the correct type of record.

```
PREFIX mcat: <http://mobi.com/ontologies/catalog#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT ?recordIRI ?title (GROUP_CONCAT(distinct ?type;separator = " | ") as ?types)
WHERE {
    ?recordIRI a mcat:Record ;
        dct:title ?title ;
        a ?type .
} GROUP BY ?recordIRI ?title
```

**Comment by JianChen123** [comment]
Thank you for the detailed explanation. Yep, I can upload the data file via UI. I found Mobi very interesting and want to explore it a bit. Is there other channel to ask questions?

**Comment by mnmercer** [comment]
No problem! We have a Jira Service Desk available [here](https://inovexirad.atlassian.net/servicedesk) where you can submit feature requests, bugs and other questions. Please let us know if you have any others questions or feedback!
